In [7]:
#DATA PREPROCESSING    important(the data must be splitted into dependant and independent columns/data.....Then for training the data is split again for training sets and test sets) other sections are implemented sometimes depending on #the dataset




#IMPORT IMPROTANT LIBRARIES

import numpy as np         #numpy is used for most of the mathematical (as np ables us to use it as a shortcut)
import matplotlib.pyplot as plt     # for charts and graphs
import pandas as pd




#IMPORTING THE DATASET
#1. ALWAYS REMEMBER TO CHANGE THE DIRECTORY OR PROVIDE THE FULL PATH


dataset = pd.read_csv('/kaggle/input/data-csv/Data.csv')       #stores all the data and columns into the array dataset
X= dataset.iloc[:, :-1].values        # stores all the values of the columns except the last one (because last one is dependant )
y= dataset.iloc[:, 3].values            # stores all the values of the last one in y (dependant)

print('Independent Variables',X)
print('Dependent Variables',y)



#TAKING CARE OF MISSING DATA
#some times there is missing data in the dataset which can be filled using the following/ there are different strategies used but the most common is mean strategy which takes the mean of the other values in the column or sometimes even #row and places the mean there

from sklearn.impute import SimpleImputer                              # library import
imputer= SimpleImputer(missing_values=np.nan, strategy = 'mean')              # setting all missing values as 'NAN' then setting the strategy as mean and storing object
imputer = imputer.fit(X[: , 1:3])
X[: , 1:3] = imputer.transform(X[:, 1:3])     

print('Independent variable after taking care of missing values',X)



#ENCODING CATEGORICAL DATA
# when there is data that can be categorized for example country names or a Boolean of yes or no, labeling can be done to give them unique numbers
# further onehotencoder can be used to give only values so that the categories cannot be valued

from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
labelencoder_X= LabelEncoder()      #Labelencoder does simple encoding which gives values to the categories which is sometime not needed    // Onehotencoder      labelencoder_X = LabelEncoder()                                       #makes separate columns       
X[:, 0]= labelencoder_X.fit_transform(X[:, 0])                         # fits label encoding into first columns and then transforms it

first_column = X[:, 0].reshape(-1, 1)
onehotencoder =OneHotEncoder()    
# inside brackets specifies that first column needs to be labeled
efc= onehotencoder.fit_transform(first_column).toarray()
X = np.hstack((efc, X[:, 1:]))

print('After Encoding',X)


#SPLITTING DATASET INTO TRAINING AND TEST SET
# the train set is the dataset that the machine learns corelations etc on and then the predicted data in tested and compared with test dataset

from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(X, y , test_size= 0.2, random_state=0)     
print('Test sets',X_test,y_test)
print('Train sets',X_train,y_train)


# Feature Scaling
#this is rarely used because most of the libraires have built-in function of scaling
# it normalizes or standardizes the values that are too much out range mostly the new range of all values is -1 to 1

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)



Independent Variables [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Dependent Variables ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
Independent variable after taking care of missing values [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
After Encoding [[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
Test 